let cleanup=[];
export function mount(root,{markComplete}){
 let replicas=3,actual=3,version='v1',old=0;
 root.innerHTML=`<div class="tabs"><button class="tab active" data-tab="reconcile">① Reconciliation</button><button class="tab" data-tab="rollout">② Rolling update</button><button class="tab" data-tab="quiz">③ Challenge</button></div>
 <section data-page="reconcile"><div class="grid-2"><div class="panel"><div class="eyebrow">Desired state lab</div><h2 style="margin-top:7px">Deployment says how many Pods should exist</h2><div class="control" style="margin-top:16px"><label>Desired replicas <strong id="desired-label">3</strong></label><input id="desired" type="range" min="1" max="8" value="3"></div><div class="chip-row"><button class="chip-btn" id="delete-pod">Delete one Pod</button><button class="chip-btn" id="kill-two">Delete two Pods</button><button class="primary-btn" id="reconcile">Run controller loop</button></div><div id="rec-explain" class="callout"></div></div><div class="panel"><div class="eyebrow">Live objects</div><div class="flow" id="pods" style="grid-template-columns:repeat(4,minmax(90px,1fr));margin-top:14px"></div><div class="grid-3" style="margin-top:14px"><div class="metric"><span>Desired</span><strong id="desired-m">3</strong></div><div class="metric"><span>Actual</span><strong id="actual-m">3</strong></div><div class="metric"><span>Drift</span><strong id="drift-m">0</strong></div></div></div></div></section>
 <section data-page="rollout" hidden><div class="grid-2"><div class="panel"><div class="eyebrow">Rolling update</div><h2 style="margin-top:7px">Change the Pod template</h2><p class="hero-copy">A Deployment does not edit existing Pods in place. A new ReplicaSet is created and the old one is gradually scaled down.</p><div class="chip-row"><button class="primary-btn" id="start-rollout">Roll out v2</button><button class="chip-btn" id="roll-step">Advance one step</button><button class="chip-btn" id="reset-rollout">Reset to v1</button></div><div id="roll-explain" class="callout"></div></div><div class="panel"><div class="eyebrow">ReplicaSets</div><div id="rs-view" style="margin-top:14px"></div></div></div></section>
 <section data-page="quiz" hidden><div class="panel"><div class="eyebrow">Quick check</div><h2 style="margin-top:7px">You manually delete a Pod owned by a Deployment. What happens?</h2><div class="quiz-options" style="margin-top:14px"><button class="chip-btn" data-answer="1">The ReplicaSet creates a replacement</button><button class="chip-btn" data-answer="0">The Deployment becomes permanently smaller</button><button class="chip-btn" data-answer="0">The scheduler recreates the Pod</button></div><div id="quiz-result"></div><button class="primary-btn" data-mark-complete style="margin-top:18px">Mark lesson complete</button></div></section>`;
 const render=()=>{root.querySelector('#desired-label').textContent=replicas;root.querySelector('#desired-m').textContent=replicas;root.querySelector('#actual-m').textContent=actual;root.querySelector('#drift-m').textContent=replicas-actual;root.querySelector('#pods').innerHTML=Array.from({length:actual},(_,i)=>`<div class="flow-step"><strong>Pod ${i+1}</strong><small>${version}</small></div>`).join('');root.querySelector('#rec-explain').innerHTML=replicas===actual?'<strong>Desired = actual</strong><p>No reconciliation action is needed.</p>':`<strong>Drift detected</strong><p>Desired ${replicas}, actual ${actual}. The controller loop will create or remove Pods through the ReplicaSet until actual state converges.</p>`};
 const renderRoll=()=>{root.querySelector('#rs-view').innerHTML=`<div class="callout success" style="margin-top:0"><strong>ReplicaSet ${version==='v1'?'rs-v1':'rs-v2'} · ${replicas-old} Pods</strong></div>${old?`<div class="callout warn"><strong>Old ReplicaSet rs-v1 · ${old} Pods</strong><p>Scaled down gradually while new Pods become available.</p></div>`:''}`};
 render();renderRoll();
 const desired=root.querySelector('#desired');let f=e=>{replicas=+e.target.value;render()};desired.addEventListener('input',f);cleanup.push(()=>desired.removeEventListener('input',f));
 [['#delete-pod',1],['#kill-two',2]].forEach(([s,n])=>{const b=root.querySelector(s),fn=()=>{actual=Math.max(0,actual-n);render()};b.addEventListener('click',fn);cleanup.push(()=>b.removeEventListener('click',fn))});
 let b=root.querySelector('#reconcile');f=()=>{actual=replicas;render()};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#start-rollout');f=()=>{if(version==='v1'){version='v2';old=replicas;root.querySelector('#roll-explain').innerHTML='<strong>New ReplicaSet created</strong><p>Now advance the rollout. Each step shifts one replica from rs-v1 to rs-v2.</p>';renderRoll()}};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#roll-step');f=()=>{if(version==='v2'&&old>0){old--;renderRoll();root.querySelector('#roll-explain').innerHTML=old?`<strong>Rollout in progress</strong><p>${old} old replica${old===1?'':'s'} remain.</p>`:'<strong>Rollout complete</strong><p>The new ReplicaSet now owns all desired replicas.</p>'}};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#reset-rollout');f=()=>{version='v1';old=0;renderRoll()};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 root.querySelectorAll('[data-answer]').forEach(x=>{const fn=()=>root.querySelector('#quiz-result').innerHTML=x.dataset.answer==='1'?'<div class="callout success"><strong>Correct.</strong><p>The controller maintains desired state; the scheduler only places the replacement after it exists.</p></div>':'<div class="callout danger"><strong>Try again.</strong><p>Ask which component owns the desired replica count.</p></div>';x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});
 const c=root.querySelector('[data-mark-complete]');c.addEventListener('click',markComplete);cleanup.push(()=>c.removeEventListener('click',markComplete));bindTabs(root)
}
function bindTabs(root){root.querySelectorAll('[data-tab]').forEach(b=>{const f=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==b.dataset.tab)};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))})}
export function unmount(){cleanup.forEach(f=>{try{f()}catch{}});cleanup=[];}
