let cleanup=[];
export function mount(root,{markComplete}){
 const cases={pending:{title:'Pod stuck Pending',steps:[['kubectl get pod -o wide','Confirms Pending and shows no node assignment.'],['kubectl describe pod','Look for scheduling Events: insufficient CPU/memory, taints, affinity, PVC constraints.'],['kubectl get nodes','Check node readiness and capacity.']]},crash:{title:'CrashLoopBackOff',steps:[['kubectl describe pod','Check restart count, last state, probes and Events.'],['kubectl logs <pod> --previous','Read logs from the previously crashed container.'],['kubectl get pod -o yaml','Inspect command, env, mounts, probes and resource settings.']]},image:{title:'ImagePullBackOff',steps:[['kubectl describe pod','Events usually expose image name, auth, registry or network errors.'],['kubectl get pod -o yaml','Verify image and imagePullSecrets.'],['kubectl get secret','Confirm referenced registry credentials exist in the namespace.']]},service:{title:'Service has no traffic',steps:[['kubectl get svc','Confirm Service selector, ports and ClusterIP.'],['kubectl get endpointslice -l kubernetes.io/service-name=<svc>','Check whether ready backend endpoints exist.'],['kubectl get pod --show-labels','Compare Pod labels with the Service selector.']]}};
 let selected='pending',index=0;
 root.innerHTML=`<div class="tabs"><button class="tab active" data-tab="lab">① Symptom → signal</button><button class="tab" data-tab="method">② Debug method</button><button class="tab" data-tab="quiz">③ Challenge</button></div>
 <section data-page="lab"><div class="grid-2"><div class="panel"><div class="eyebrow">Troubleshooting simulator</div><h2 style="margin-top:7px">Start from the symptom, not random commands</h2><div class="chip-row" style="margin-top:16px">${Object.entries(cases).map(([k,v])=>`<button class="chip-btn ${k==='pending'?'active':''}" data-case="${k}">${v.title}</button>`).join('')}</div><div id="case-summary" class="callout"></div><button class="primary-btn" id="next-step" style="margin-top:12px">Run next diagnostic</button></div><div class="panel"><div class="eyebrow">Evidence trail</div><div id="trail" style="margin-top:14px"></div></div></div></section>
 <section data-page="method" hidden><div class="panel"><div class="eyebrow">Production habit</div><h2 style="margin-top:7px">Use an evidence funnel</h2><div class="flow" style="margin-top:16px"><div class="flow-step active"><strong>1. State</strong><small>get / wide</small></div><div class="flow-step"><strong>2. Events</strong><small>describe</small></div><div class="flow-step"><strong>3. Logs</strong><small>current/previous</small></div><div class="flow-step"><strong>4. Spec</strong><small>yaml</small></div><div class="flow-step"><strong>5. Dependencies</strong><small>svc/dns/pvc/node</small></div><div class="flow-step"><strong>6. Metrics</strong><small>resource pressure</small></div></div><div class="callout success"><strong>Rule of thumb</strong><p>Ask “what evidence would disprove my current hypothesis?” before running the next command. Kubernetes debugging is faster when each command narrows the search space.</p></div></div></section>
 <section data-page="quiz" hidden><div class="panel"><div class="eyebrow">Quick check</div><h2 style="margin-top:7px">A container restarted before you inspected it. Which command is especially useful?</h2><div class="quiz-options" style="margin-top:14px"><button class="chip-btn" data-answer="0">kubectl top node</button><button class="chip-btn" data-answer="1">kubectl logs &lt;pod&gt; --previous</button><button class="chip-btn" data-answer="0">kubectl api-resources</button></div><div id="quiz-result"></div><button class="primary-btn" data-mark-complete style="margin-top:18px">Mark lesson complete</button></div></section>`;
 const render=()=>{const c=cases[selected];root.querySelector('#case-summary').innerHTML=`<strong>${c.title}</strong><p>Run diagnostics in order and notice how each command answers a specific question.</p>`;root.querySelector('#trail').innerHTML=c.steps.map((s,i)=>`<div class="callout ${i<index?'success':''}" style="margin-top:${i?'10':'0'};opacity:${i<index?1:.45}"><strong>${i+1}. <code>${s[0]}</code></strong><p>${i<index?s[1]:'Not run yet'}</p></div>`).join('');root.querySelector('#next-step').textContent=index>=c.steps.length?'Reset case':'Run next diagnostic'};render();
 root.querySelectorAll('[data-case]').forEach(b=>{const f=()=>{selected=b.dataset.case;index=0;root.querySelectorAll('[data-case]').forEach(x=>x.classList.toggle('active',x===b));render()};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))});
 const next=root.querySelector('#next-step');let f=()=>{const c=cases[selected];if(index>=c.steps.length)index=0;else index++;render()};next.addEventListener('click',f);cleanup.push(()=>next.removeEventListener('click',f));
 root.querySelectorAll('[data-answer]').forEach(x=>{const fn=()=>root.querySelector('#quiz-result').innerHTML=x.dataset.answer==='1'?'<div class="callout success"><strong>Correct.</strong><p><code>--previous</code> retrieves logs from the previous terminated container instance when available.</p></div>':'<div class="callout danger"><strong>Try again.</strong><p>You need evidence from the container instance that already crashed.</p></div>';x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});const c=root.querySelector('[data-mark-complete]');c.addEventListener('click',markComplete);cleanup.push(()=>c.removeEventListener('click',markComplete));bindTabs(root)
}
function bindTabs(root){root.querySelectorAll('[data-tab]').forEach(b=>{const f=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==b.dataset.tab)};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))})}
export function unmount(){cleanup.forEach(f=>{try{f()}catch{}});cleanup=[];}
