let cleanup=[];
export function mount(root,{markComplete}){
 let request=512,limit=1024,usage=700,nodeRequested=2500,nodeCapacity=4096;
 root.innerHTML=`<div class="tabs"><button class="tab active" data-tab="schedule">① Schedule memory</button><button class="tab" data-tab="runtime">② Hit the limit</button><button class="tab" data-tab="quiz">③ Challenge</button></div>
 <section data-page="schedule"><div class="grid-2"><div class="panel"><div class="eyebrow">Placement</div><h2 style="margin-top:7px">Memory request decides whether the Pod fits</h2><div class="control" style="margin-top:16px"><label>Pod request <strong id="req-label">512 Mi</strong></label><input id="mem-req" type="range" min="128" max="2048" step="128" value="512"></div><div class="control"><label>Existing requested memory <strong id="node-req-label">2500 Mi</strong></label><input id="node-req" type="range" min="0" max="4000" step="128" value="2500"></div><div id="fit-result" class="callout"></div></div><div class="panel"><div class="eyebrow">4 Gi node</div><div class="metric" style="margin-top:14px"><span>Node capacity</span><strong>4096 Mi</strong></div><div class="node-row"><span>Existing requests</span><strong id="node-req-m"></strong></div><div class="bar req"><i id="node-req-bar"></i></div><div class="node-row"><span>After this Pod</span><strong id="after-m"></strong></div><div class="bar quota"><i id="after-bar"></i></div></div></div></section>
 <section data-page="runtime" hidden><div class="grid-2"><div class="panel"><div class="eyebrow">Runtime</div><h2 style="margin-top:7px">Memory is not CPU</h2><p class="hero-copy">CPU can be bandwidth-throttled. Memory usage crossing a cgroup limit can instead lead to allocation failure and OOM killing.</p><div class="control"><label>Memory limit <strong id="limit-label">1024 Mi</strong></label><input id="mem-limit" type="range" min="256" max="2048" step="128" value="1024"></div><div class="control"><label>Working set / demand <strong id="usage-label">700 Mi</strong></label><input id="mem-use" type="range" min="128" max="2500" step="64" value="700"></div><button class="primary-btn" id="allocate">Simulate allocation</button></div><div class="panel"><div class="eyebrow">Outcome</div><div id="runtime-result" class="callout" style="margin-top:14px"></div><div class="math-box" id="runtime-math"></div></div></div></section>
 <section data-page="quiz" hidden><div class="panel"><div class="eyebrow">Quick check</div><h2 style="margin-top:7px">A container exceeds its memory limit. What is the closest CPU analogy?</h2><div class="quiz-options" style="margin-top:14px"><button class="chip-btn" data-answer="0">It simply waits for the next 100 ms period</button><button class="chip-btn" data-answer="1">There is no direct equivalent; it may be OOM-killed instead of throttled like CPU</button></div><div id="quiz-result"></div><button class="primary-btn" data-mark-complete style="margin-top:18px">Mark lesson complete</button></div></section>`;
 const renderFit=()=>{root.querySelector('#req-label').textContent=request+' Mi';root.querySelector('#node-req-label').textContent=nodeRequested+' Mi';root.querySelector('#node-req-m').textContent=nodeRequested+' Mi';root.querySelector('#after-m').textContent=nodeRequested+request+' Mi';root.querySelector('#node-req-bar').style.width=Math.min(100,nodeRequested/nodeCapacity*100)+'%';root.querySelector('#after-bar').style.width=Math.min(100,(nodeRequested+request)/nodeCapacity*100)+'%';const fits=nodeRequested+request<=nodeCapacity;root.querySelector('#fit-result').className='callout '+(fits?'success':'danger');root.querySelector('#fit-result').innerHTML=fits?`<strong>Pod fits</strong><p>${nodeCapacity-nodeRequested} Mi is unrequested; this Pod asks for ${request} Mi.</p>`:`<strong>Pod stays Pending</strong><p>Requests would total ${nodeRequested+request} Mi, above the node's ${nodeCapacity} Mi capacity in this simplified model.</p>`};
 const renderRuntime=()=>{root.querySelector('#limit-label').textContent=limit+' Mi';root.querySelector('#usage-label').textContent=usage+' Mi';const over=usage>limit;root.querySelector('#runtime-result').className='callout '+(over?'danger':'success');root.querySelector('#runtime-result').innerHTML=over?`<strong>OOM risk / container termination</strong><p>Demand ${usage} Mi exceeds the configured ${limit} Mi cgroup memory ceiling. Under pressure, the kernel can invoke OOM handling rather than periodically throttling memory like CPU bandwidth.</p>`:`<strong>Within the memory limit</strong><p>${limit-usage} Mi of configured headroom remains.</p>`;root.querySelector('#runtime-math').innerHTML=`request = ${request} Mi → scheduling/accounting<br>limit = ${limit} Mi → cgroup memory ceiling<br>usage = ${usage} Mi → observed/runtime demand<br><br><span style="color:${over?'var(--red)':'var(--green)'}">${over?'usage > limit → not a CPU-style throttle':'usage ≤ limit'}</span>`};renderFit();renderRuntime();
 [['#mem-req','request',renderFit],['#node-req','nodeRequested',renderFit],['#mem-limit','limit',renderRuntime],['#mem-use','usage',renderRuntime]].forEach(([s,k,render])=>{const e=root.querySelector(s),f=ev=>{if(k==='request')request=+ev.target.value;if(k==='nodeRequested')nodeRequested=+ev.target.value;if(k==='limit')limit=+ev.target.value;if(k==='usage')usage=+ev.target.value;render()};e.addEventListener('input',f);cleanup.push(()=>e.removeEventListener('input',f))});
 const a=root.querySelector('#allocate'),af=()=>renderRuntime();a.addEventListener('click',af);cleanup.push(()=>a.removeEventListener('click',af));
 root.querySelectorAll('[data-answer]').forEach(x=>{const fn=()=>root.querySelector('#quiz-result').innerHTML=x.dataset.answer==='1'?'<div class="callout success"><strong>Correct.</strong><p>CPU and memory limits fail differently. That distinction matters a lot in production diagnosis.</p></div>':'<div class="callout danger"><strong>Try again.</strong><p>A memory limit is not implemented as a replenishing CPU bandwidth quota.</p></div>';x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});const c=root.querySelector('[data-mark-complete]');c.addEventListener('click',markComplete);cleanup.push(()=>c.removeEventListener('click',markComplete));bindTabs(root)
}
function bindTabs(root){root.querySelectorAll('[data-tab]').forEach(b=>{const f=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==b.dataset.tab)};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))})}
export function unmount(){cleanup.forEach(f=>{try{f()}catch{}});cleanup=[];}
