let cleanup=[];
export function mount(root,{markComplete}){
 const state={denyApi:false,allowFrontendApi:false,denyDb:false,allowApiDb:false};
 const flows=[['frontend','api'],['debug','api'],['api','db'],['frontend','db']];
 root.innerHTML=`<div class="grid-2"><div class="panel"><div class="eyebrow">Traffic policy lab</div><h2>NetworkPolicy</h2><p style="color:var(--muted)">Start open, then select destination Pods with ingress policies and add explicit allows.</p><div class="chip-row" style="margin:14px 0"><button class="chip-btn" id="deny-api">Default-deny ingress to api</button><button class="chip-btn" id="allow-fa">Allow frontend → api</button><button class="chip-btn" id="deny-db">Default-deny ingress to db</button><button class="chip-btn" id="allow-ad">Allow api → db</button></div><div id="flows"></div></div><div class="panel"><div class="eyebrow">Policy reasoning</div><div id="explain"></div><div class="terminal" id="yaml" style="margin-top:14px"></div></div></div><div class="callout warn" style="margin-top:14px"><strong>NetworkPolicy only works when the cluster network implementation enforces it</strong><p>The Kubernetes API defines policy intent; the networking plugin/dataplane must implement enforcement. Also remember: ingress rules on a destination and egress rules on a source are separate directions.</p></div><div class="panel" style="margin-top:14px"><button class="primary-btn" data-mark-complete>Mark lesson complete</button></div>`;
 const $=s=>root.querySelector(s);function allowed(a,b){if(b==='api'&&state.denyApi)return a==='frontend'&&state.allowFrontendApi;if(b==='db'&&state.denyDb)return a==='api'&&state.allowApiDb;return true;}
 function render(){$('#flows').innerHTML=flows.map(([a,b])=>{const ok=allowed(a,b);return `<div class="callout ${ok?'success':'danger'}" style="margin-top:8px"><strong>${a} → ${b}: ${ok?'ALLOW':'DROP'}</strong><p>${ok?'Traffic is permitted by the current simplified policy set.':'Destination is isolated for ingress and no matching allow rule exists.'}</p></div>`}).join('');$('#explain').innerHTML=`<div class="metric"><span>api isolation</span><strong>${state.denyApi?'selected by ingress deny policy':'not isolated'}</strong></div><div class="metric" style="margin-top:8px"><span>db isolation</span><strong>${state.denyDb?'selected by ingress deny policy':'not isolated'}</strong></div><div class="callout" style="margin-top:12px"><strong>Key rule</strong><p>If no NetworkPolicy selects a Pod for a direction, that direction is allowed by default. Once selected, allowed peers/ports are the union of matching policies for that direction.</p></div>`;$('#yaml').textContent=`# simplified intent\napi ingress: ${state.denyApi?(state.allowFrontendApi?'only frontend':'deny all'):'allow all'}\ndb ingress:  ${state.denyDb?(state.allowApiDb?'only api':'deny all'):'allow all'}`;[['#deny-api',state.denyApi],['#allow-fa',state.allowFrontendApi],['#deny-db',state.denyDb],['#allow-ad',state.allowApiDb]].forEach(([s,on])=>$(s).classList.toggle('active',on));}
 const bind=(s,k)=>{const el=$(s),fn=()=>{state[k]=!state[k];render()};el.addEventListener('click',fn);cleanup.push(()=>el.removeEventListener('click',fn))};bind('#deny-api','denyApi');bind('#allow-fa','allowFrontendApi');bind('#deny-db','denyDb');bind('#allow-ad','allowApiDb');const done=()=>markComplete();root.querySelector('[data-mark-complete]').addEventListener('click',done);cleanup.push(()=>root.querySelector('[data-mark-complete]')?.removeEventListener('click',done));render();}
export function unmount(){cleanup.forEach(fn=>{try{fn()}catch{}});cleanup=[];}
