let cleanup=[];
export function mount(root,{markComplete}){
 let podIp='10.244.1.21',generation=1,sidecar=true;
 root.innerHTML=`<div class="tabs"><button class="tab active" data-tab="model">① Pod model</button><button class="tab" data-tab="replace">② Replace a Pod</button><button class="tab" data-tab="quiz">③ Challenge</button></div>
 <section data-page="model"><div class="grid-2"><div class="panel"><div class="eyebrow">Smallest schedulable workload</div><h2 style="margin-top:7px">A Pod can contain multiple cooperating containers</h2><p class="hero-copy">Containers in one Pod share the Pod network namespace and can communicate over localhost. They also share volumes explicitly mounted into both containers.</p><div class="chip-row"><button class="primary-btn" id="localhost">Call localhost:9090</button><button class="chip-btn" id="toggle-sidecar">Stop sidecar</button></div><div id="pod-result" class="callout"></div></div><div class="panel"><div class="eyebrow">One Pod sandbox</div><div class="node selected" style="margin-top:14px"><div class="node-head"><strong>web-${generation}</strong><span id="ip-label">${podIp}</span></div><div class="grid-2"><div class="metric"><span>Container</span><strong>app :8080</strong></div><div class="metric"><span>Container</span><strong id="sidecar-label">sidecar :9090</strong></div></div><div class="callout success"><strong>Shared network namespace</strong><p>Both containers see the same Pod IP. Inside the Pod, app can reach sidecar at <code>localhost:9090</code>.</p></div></div></div></div></section>
 <section data-page="replace" hidden><div class="grid-2"><div class="panel"><div class="eyebrow">Pods are replaceable</div><h2 style="margin-top:7px">Delete and recreate</h2><p class="hero-copy">A replacement Pod is a new object/sandbox and can receive a different IP. Higher-level controllers and Services give applications continuity around replaceable Pods.</p><button class="primary-btn" id="replace-pod">Replace Pod</button></div><div class="panel"><div class="eyebrow">Identity change</div><div id="replace-result" class="callout" style="margin-top:14px"><strong>Current Pod</strong><p>web-${generation} · ${podIp}</p></div></div></div></section>
 <section data-page="quiz" hidden><div class="panel"><div class="eyebrow">Quick check</div><h2 style="margin-top:7px">Two containers are in the same Pod. How can one reach the other on port 9090?</h2><div class="quiz-options" style="margin-top:14px"><button class="chip-btn" data-answer="1">localhost:9090</button><button class="chip-btn" data-answer="0">It always needs a Kubernetes Service</button><button class="chip-btn" data-answer="0">The kube-scheduler proxies the request</button></div><div id="quiz-result"></div><button class="primary-btn" data-mark-complete style="margin-top:18px">Mark lesson complete</button></div></section>`;
 const result=root.querySelector('#pod-result');result.innerHTML='<strong>Both containers running</strong><p>Try the localhost call.</p>';
 let b=root.querySelector('#localhost'),f=()=>{result.innerHTML=sidecar?'<strong>200 OK from localhost:9090</strong><p>The call never needs to leave the Pod network namespace.</p>':'<strong>Connection refused</strong><p>The Pod network namespace still exists, but nothing is listening on port 9090.</p>'};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#toggle-sidecar');f=()=>{sidecar=!sidecar;b.textContent=sidecar?'Stop sidecar':'Start sidecar';root.querySelector('#sidecar-label').textContent=sidecar?'sidecar :9090':'sidecar stopped';result.innerHTML=`<strong>Sidecar ${sidecar?'running':'stopped'}</strong><p>${sidecar?'localhost:9090 is available again.':'The app container can remain running while its sibling container is down.'}</p>`};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#replace-pod');f=()=>{const old=podIp;generation++;podIp=`10.244.1.${20+generation}`;root.querySelector('#replace-result').innerHTML=`<strong>Old Pod gone: ${old}</strong><p>New Pod <strong>web-${generation}</strong> has IP <strong>${podIp}</strong>. Do not build stable application identity around an individual Pod IP.</p>`};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 root.querySelectorAll('[data-answer]').forEach(x=>{const fn=()=>root.querySelector('#quiz-result').innerHTML=x.dataset.answer==='1'?'<div class="callout success"><strong>Correct.</strong><p>Containers in the same Pod share its network namespace.</p></div>':'<div class="callout danger"><strong>Try again.</strong><p>Think about what the containers share inside one Pod sandbox.</p></div>';x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});const c=root.querySelector('[data-mark-complete]');c.addEventListener('click',markComplete);cleanup.push(()=>c.removeEventListener('click',markComplete));bindTabs(root)
}
function bindTabs(root){root.querySelectorAll('[data-tab]').forEach(b=>{const f=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==b.dataset.tab)};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))})}
export function unmount(){cleanup.forEach(f=>{try{f()}catch{}});cleanup=[];}
