let cleanup=[];
export function mount(root,{markComplete}){
 let size=10,sc='fast',policy='Delete',bound=false,pod=false;
 root.innerHTML=`<div class="tabs"><button class="tab active" data-tab="claim">① Claim storage</button><button class="tab" data-tab="lifecycle">② Lifecycle</button><button class="tab" data-tab="quiz">③ Challenge</button></div>
 <section data-page="claim"><div class="grid-2"><div class="panel"><div class="eyebrow">Dynamic provisioning lab</div><h2 style="margin-top:7px">Create a PVC</h2><div class="control" style="margin-top:16px"><label>Requested size <strong id="size-label">10 Gi</strong></label><input id="size" type="range" min="1" max="100" value="10"></div><div class="control"><label>StorageClass</label><select id="sc"><option value="fast">fast · SSD</option><option value="standard">standard · balanced</option><option value="archive">archive · cheap</option></select></div><div class="control"><label>Reclaim policy</label><select id="policy"><option>Delete</option><option>Retain</option></select></div><div class="chip-row"><button class="primary-btn" id="create-pvc">Create PVC</button><button class="chip-btn" id="attach">Attach Pod</button><button class="chip-btn" id="reset">Reset</button></div><div id="storage-result" class="callout"></div></div><div class="panel"><div class="eyebrow">What exists now</div><div id="storage-flow" style="margin-top:14px"></div></div></div></section>
 <section data-page="lifecycle" hidden><div class="panel"><div class="eyebrow">Object lifetimes</div><h2 style="margin-top:7px">Pod storage vs persistent storage</h2><div class="flow" style="margin-top:16px"><div class="flow-step"><strong>Pod</strong><small>consumes a claim</small></div><div class="flow-step"><strong>PVC</strong><small>request for storage</small></div><div class="flow-step"><strong>PV</strong><small>cluster storage resource</small></div><div class="flow-step"><strong>CSI / backend</strong><small>actual disk/share</small></div></div><div class="callout"><strong>Core idea</strong><p>A PV has a lifecycle independent of the Pod using it. Deleting and recreating a Pod does not automatically destroy a PVC-backed volume.</p></div><div class="callout warn"><strong>Reclaim policy matters after the claim is released</strong><p><strong>Delete</strong> normally removes dynamically provisioned backing storage. <strong>Retain</strong> preserves the PV/backing asset for manual handling.</p></div></div></section>
 <section data-page="quiz" hidden><div class="panel"><div class="eyebrow">Quick check</div><h2 style="margin-top:7px">A Pod using a PVC crashes and is recreated. What normally happens to the PVC?</h2><div class="quiz-options" style="margin-top:14px"><button class="chip-btn" data-answer="1">It remains and the replacement Pod can mount it</button><button class="chip-btn" data-answer="0">It is always deleted with the Pod</button><button class="chip-btn" data-answer="0">The scheduler converts it into emptyDir</button></div><div id="quiz-result"></div><button class="primary-btn" data-mark-complete style="margin-top:18px">Mark lesson complete</button></div></section>`;
 const render=()=>{root.querySelector('#size-label').textContent=size+' Gi';root.querySelector('#storage-flow').innerHTML=`<div class="flow" style="grid-template-columns:repeat(4,minmax(110px,1fr))"><div class="flow-step ${pod?'active':''}"><strong>Pod</strong><small>${pod?'mounted /data':'not attached'}</small></div><div class="flow-step ${bound?'active':''}"><strong>PVC</strong><small>${bound?'Bound':'Pending / absent'}</small></div><div class="flow-step ${bound?'active':''}"><strong>PV</strong><small>${bound?size+' Gi · '+sc:'not provisioned'}</small></div><div class="flow-step ${bound?'active':''}"><strong>Storage</strong><small>${bound?'backend volume exists':'none yet'}</small></div></div>`};render();
 let b=root.querySelector('#size'),f=e=>{size=+e.target.value;render()};b.addEventListener('input',f);cleanup.push(()=>b.removeEventListener('input',f));b=root.querySelector('#sc');f=e=>{sc=e.target.value;render()};b.addEventListener('change',f);cleanup.push(()=>b.removeEventListener('change',f));b=root.querySelector('#policy');f=e=>policy=e.target.value;b.addEventListener('change',f);cleanup.push(()=>b.removeEventListener('change',f));
 b=root.querySelector('#create-pvc');f=()=>{bound=true;render();root.querySelector('#storage-result').innerHTML=`<strong>PVC Bound</strong><p>The ${sc} StorageClass dynamically provisions a ${size} Gi PV/backing volume that satisfies the claim in this simulation.</p>`};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#attach');f=()=>{if(!bound){root.querySelector('#storage-result').innerHTML='<strong>PVC is not Bound yet</strong><p>Create the claim first.</p>';return}pod=true;render();root.querySelector('#storage-result').innerHTML='<strong>Pod mounted the claim</strong><p>The Pod references the PVC; it does not need to know the cloud disk identifier.</p>'};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#reset');f=()=>{bound=false;pod=false;render();root.querySelector('#storage-result').innerHTML='<strong>Start with a claim.</strong><p>Pick a size and StorageClass, then provision it.</p>'};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));f();
 root.querySelectorAll('[data-answer]').forEach(x=>{const fn=()=>root.querySelector('#quiz-result').innerHTML=x.dataset.answer==='1'?'<div class="callout success"><strong>Correct.</strong><p>The claim is a separate API object and can outlive individual Pods.</p></div>':'<div class="callout danger"><strong>Try again.</strong><p>PersistentVolume storage is deliberately decoupled from a single Pod lifecycle.</p></div>';x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});const c=root.querySelector('[data-mark-complete]');c.addEventListener('click',markComplete);cleanup.push(()=>c.removeEventListener('click',markComplete));bindTabs(root)
}
function bindTabs(root){root.querySelectorAll('[data-tab]').forEach(b=>{const f=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==b.dataset.tab)};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))})}
export function unmount(){cleanup.forEach(f=>{try{f()}catch{}});cleanup=[];}
