let cleanup=[];
export function mount(root,{markComplete}){
 const state={usedCpu:4,usedMem:8,quotaCpu:8,quotaMem:16,reqCpu:1,limitCpu:2,reqMem:2,limitMem:4,minCpu:.1,maxCpu:4};
 root.innerHTML=`<div class="grid-2"><div class="panel"><div class="eyebrow">Namespace admission lab</div><h2>Can this Pod be admitted?</h2>
 ${[['reqCpu','CPU request',0,5,.1],['limitCpu','CPU limit',0,6,.1],['reqMem','Memory request (Gi)',0,10,.5],['limitMem','Memory limit (Gi)',0,12,.5]].map(([id,label,min,max,step])=>`<div class="control"><label>${label}<span id="${id}-v"></span></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${state[id]}"></div>`).join('')}
 </div><div class="panel"><div class="eyebrow">Admission result</div><div id="decision"></div><div class="grid-2" style="margin-top:12px"><div class="metric"><span>Namespace CPU</span><strong id="cpu-usage"></strong></div><div class="metric"><span>Namespace memory</span><strong id="mem-usage"></strong></div></div></div></div>
 <div class="grid-3" style="margin-top:14px"><div class="metric"><span>ResourceQuota</span><strong>Caps aggregate namespace usage</strong><p style="color:var(--muted);font-size:12px">Think team/project budget across many objects.</p></div><div class="metric"><span>LimitRange</span><strong>Constrains individual objects</strong><p style="color:var(--muted);font-size:12px">Can define defaults plus min/max requests and limits.</p></div><div class="metric"><span>Scheduler</span><strong>Still checks node fit later</strong><p style="color:var(--muted);font-size:12px">Admission passing does not guarantee a node can schedule the Pod.</p></div></div><div class="panel" style="margin-top:14px"><button class="primary-btn" data-mark-complete>Mark lesson complete</button></div>`;
 const $=s=>root.querySelector(s);
 function render(){['reqCpu','limitCpu','reqMem','limitMem'].forEach(k=>{$(`#${k}-v`).textContent=state[k]+(k.includes('Mem')?' Gi':' CPU')});
 const errs=[];if(state.reqCpu<state.minCpu)errs.push(`CPU request is below LimitRange minimum ${state.minCpu}`);if(state.limitCpu>state.maxCpu)errs.push(`CPU limit is above LimitRange maximum ${state.maxCpu}`);if(state.reqCpu>state.limitCpu)errs.push('CPU request cannot exceed CPU limit in this lab');if(state.reqMem>state.limitMem)errs.push('memory request exceeds memory limit');if(state.usedCpu+state.reqCpu>state.quotaCpu)errs.push('namespace CPU request quota would be exceeded');if(state.usedMem+state.reqMem>state.quotaMem)errs.push('namespace memory request quota would be exceeded');
 const ok=!errs.length;$('#decision').innerHTML=`<div class="callout ${ok?'success':'danger'}"><strong>${ok?'ADMITTED':'REJECTED'}</strong><p>${ok?'The object satisfies the simplified LimitRange and ResourceQuota checks. Admission succeeds; scheduling is the next phase.':errs.join(' · ')}</p></div>`;$('#cpu-usage').textContent=`${state.usedCpu + state.reqCpu} / ${state.quotaCpu} CPU requested`;$('#mem-usage').textContent=`${state.usedMem + state.reqMem} / ${state.quotaMem} Gi requested`;}
 ['reqCpu','limitCpu','reqMem','limitMem'].forEach(k=>{const el=$('#'+k),fn=()=>{state[k]=Number(el.value);render()};el.addEventListener('input',fn);cleanup.push(()=>el.removeEventListener('input',fn))});const done=()=>markComplete();root.querySelector('[data-mark-complete]').addEventListener('click',done);cleanup.push(()=>root.querySelector('[data-mark-complete]')?.removeEventListener('click',done));render();}
export function unmount(){cleanup.forEach(fn=>{try{fn()}catch{}});cleanup=[];}
