let cleanup=[];
export function mount(root,{markComplete}){
 let ready=[true,true,true],requests=0;
 root.innerHTML=`<div class="tabs"><button class="tab active" data-tab="service">① Service routing</button><button class="tab" data-tab="dns">② DNS</button><button class="tab" data-tab="types">③ Service types</button><button class="tab" data-tab="quiz">④ Challenge</button></div>
 <section data-page="service"><div class="grid-2"><div class="panel"><div class="eyebrow">Stable frontend, replaceable Pods</div><h2 style="margin-top:7px">Send traffic through a Service</h2><p class="hero-copy">A Service selects matching, ready backends. Pod IPs can change; clients use the stable Service identity.</p><div class="chip-row"><button class="primary-btn" id="send">Send request</button><button class="chip-btn" id="reset">Reset</button></div><div id="route-result" class="callout"><strong>No request yet.</strong><p>Toggle readiness below, then send traffic.</p></div></div><div class="panel"><div class="eyebrow">Endpoints</div><div id="pod-grid" class="node-grid" style="margin-top:14px"></div></div></div></section>
 <section data-page="dns" hidden><div class="grid-2"><div class="panel"><div class="eyebrow">Cluster DNS</div><h2 style="margin-top:7px">Resolve a Service name</h2><div class="control" style="margin-top:16px"><label>Client namespace</label><select id="client-ns"><option>shop</option><option>payments</option></select></div><div class="control"><label>Name to resolve</label><select id="dns-name"><option>api</option><option>api.shop</option><option>api.shop.svc.cluster.local</option></select></div><button class="primary-btn" id="resolve">Resolve</button></div><div class="panel"><div class="eyebrow">DNS result</div><div id="dns-result" class="callout" style="margin-top:14px"></div></div></div></section>
 <section data-page="types" hidden><div class="panel"><div class="eyebrow">Exposure model</div><h2 style="margin-top:7px">Choose a Service type</h2><div class="chip-row" style="margin-top:16px">${['ClusterIP','NodePort','LoadBalancer','ExternalName'].map(x=>`<button class="chip-btn" data-type="${x}">${x}</button>`).join('')}</div><div id="type-result" class="callout"></div></div></section>
 <section data-page="quiz" hidden><div class="panel"><div class="eyebrow">Quick check</div><h2 style="margin-top:7px">A Pod is Ready=false. Should a normal Service send new traffic to it?</h2><div class="quiz-options" style="margin-top:14px"><button class="chip-btn" data-answer="0">Yes, readiness only affects kubectl status</button><button class="chip-btn" data-answer="1">No, it should be removed from ready endpoints</button></div><div id="quiz-result"></div><button class="primary-btn" data-mark-complete style="margin-top:18px">Mark lesson complete</button></div></section>`;
 const renderPods=()=>{root.querySelector('#pod-grid').innerHTML=ready.map((r,i)=>`<button class="node ${r?'selected':''}" data-pod="${i}" style="cursor:pointer"><div class="node-head"><strong>api-${i+1}</strong><span>${r?'Ready':'NotReady'}</span></div><div class="metric"><span>Pod IP</span><strong style="font-size:14px">10.244.1.${21+i}</strong></div><p style="color:var(--muted);font-size:12px">Click to toggle readiness</p></button>`);root.querySelectorAll('[data-pod]').forEach(b=>{const fn=()=>{ready[+b.dataset.pod]=!ready[+b.dataset.pod];renderPods()};b.addEventListener('click',fn);cleanup.push(()=>b.removeEventListener('click',fn))})};renderPods();
 let b=root.querySelector('#send'),f=()=>{const candidates=ready.map((v,i)=>v?i:-1).filter(i=>i>=0);requests++;root.querySelector('#route-result').innerHTML=candidates.length?`<strong>Request #${requests} → api-${candidates[(requests-1)%candidates.length]+1}</strong><p>The Service routes to a ready backend. This visualization uses round-robin for teaching; actual dataplane selection depends on the implementation.</p>`:'<strong>No ready endpoints</strong><p>The Service exists, but there is nowhere healthy to send this request.</p>'};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#reset');f=()=>{ready=[true,true,true];requests=0;renderPods();root.querySelector('#route-result').innerHTML='<strong>No request yet.</strong><p>Toggle readiness below, then send traffic.</p>'};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 b=root.querySelector('#resolve');f=()=>{const ns=root.querySelector('#client-ns').value,n=root.querySelector('#dns-name').value;let ok=n.includes('.')||ns==='shop';root.querySelector('#dns-result').innerHTML=ok?`<strong>${n} → 10.96.42.10</strong><p>${n==='api'?'Short names are searched in the client Pod\'s namespace. ':''}The Service DNS name resolves to its stable virtual IP in this example.</p>`:`<strong>NXDOMAIN / no match in ${ns}</strong><p>The short name <code>api</code> searches the client namespace. Use <code>api.shop</code> or the full service DNS name to cross namespaces.</p>`};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f));
 const types={ClusterIP:'Reachable inside the cluster through a stable virtual IP. This is the default Service type.',NodePort:'Also exposes the Service on a port on each node. External clients can target nodeIP:nodePort if network access allows it.',LoadBalancer:'Asks the environment/cloud integration to provision or attach an external load balancer to the Service.',ExternalName:'Returns a DNS CNAME-style mapping to an external DNS name instead of proxying to Pod endpoints.'};root.querySelectorAll('[data-type]').forEach(x=>{const fn=()=>{root.querySelectorAll('[data-type]').forEach(y=>y.classList.toggle('active',y===x));root.querySelector('#type-result').innerHTML=`<strong>${x.dataset.type}</strong><p>${types[x.dataset.type]}</p>`};x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});root.querySelector('[data-type="ClusterIP"]').click();
 root.querySelectorAll('[data-answer]').forEach(x=>{const fn=()=>root.querySelector('#quiz-result').innerHTML=x.dataset.answer==='1'?'<div class="callout success"><strong>Correct.</strong><p>Readiness is used to keep unhealthy/not-ready backends out of normal Service traffic.</p></div>':'<div class="callout danger"><strong>Not quite.</strong><p>Readiness exists specifically to signal whether a workload should receive normal traffic.</p></div>';x.addEventListener('click',fn);cleanup.push(()=>x.removeEventListener('click',fn))});const c=root.querySelector('[data-mark-complete]');c.addEventListener('click',markComplete);cleanup.push(()=>c.removeEventListener('click',markComplete));bindTabs(root)
}
function bindTabs(root){root.querySelectorAll('[data-tab]').forEach(b=>{const f=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==b.dataset.tab)};b.addEventListener('click',f);cleanup.push(()=>b.removeEventListener('click',f))})}
export function unmount(){cleanup.forEach(f=>{try{f()}catch{}});cleanup=[];}
