let cleanup=[];
export function mount(root,{markComplete}){
 const state={replicas:3,deleted:null,step:0};
 root.innerHTML=`<div class="grid-2"><div class="panel"><div class="eyebrow">Stable identity simulator</div><h2>StatefulSet</h2><div class="control"><label>Replicas <span id="rep-v"></span></label><input id="rep" type="range" min="1" max="5" value="3"></div><div class="chip-row"><button class="primary-btn" id="delete">Delete db-1 Pod</button><button class="chip-btn" id="scale-down">Scale down by 1</button><button class="chip-btn" id="scale-up">Scale up by 1</button></div><div id="pods" class="node-grid" style="margin-top:14px"></div></div>
 <div class="panel"><div class="eyebrow">What stays stable?</div><div id="explain"></div><div class="terminal" id="dns" style="margin-top:14px"></div></div></div>
 <div class="grid-3" style="margin-top:14px"><div class="metric"><span>Pod identity</span><strong>db-0, db-1, db-2…</strong><p style="color:var(--muted);font-size:12px">Ordinals are stable and predictable.</p></div><div class="metric"><span>Storage identity</span><strong>One PVC per ordinal</strong><p style="color:var(--muted);font-size:12px">Recreated Pods can reattach the same claim.</p></div><div class="metric"><span>Networking</span><strong>Stable DNS with headless Service</strong><p style="color:var(--muted);font-size:12px">Useful when peer identity matters.</p></div></div><div class="panel" style="margin-top:14px"><button class="primary-btn" data-mark-complete>Mark lesson complete</button></div>`;
 const $=s=>root.querySelector(s);
 function render(){$('#rep-v').textContent=state.replicas;const cards=[];for(let i=0;i<state.replicas;i++){const missing=state.deleted===i;cards.push(`<div class="node ${missing?'':'selected'}"><div class="node-head"><strong>db-${i}</strong><span>${missing?'recreating':'Running'}</span></div><div class="metric"><span>PVC</span><strong>data-db-${i}</strong></div><div class="metric" style="margin-top:8px"><span>DNS</span><strong style="font-size:13px">db-${i}.db.default.svc</strong></div></div>`)}$('#pods').innerHTML=cards.join('');$('#explain').innerHTML=`<div class="callout ${state.deleted!==null?'warn':'success'}"><strong>${state.deleted!==null?`db-${state.deleted} was deleted`:'Stable identities intact'}</strong><p>${state.deleted!==null?`The controller recreates db-${state.deleted} with the same ordinal. Its PVC data-db-${state.deleted} remains the identity of that replica.`:'Scaling changes the highest ordinals. StatefulSet is for workloads where identity/order/storage association matters.'}</p></div>`;$('#dns').textContent=`Pod           PVC            DNS\n${Array.from({length:state.replicas},(_,i)=>`db-${i}          data-db-${i}      db-${i}.db.default.svc`).join('\n')}`;}
 const rep=$('#rep'),rf=()=>{state.replicas=Number(rep.value);state.deleted=null;render()};rep.addEventListener('input',rf);cleanup.push(()=>rep.removeEventListener('input',rf));
 const del=()=>{if(state.replicas>1){state.deleted=1;render();setTimeout(()=>{if(state.deleted===1){state.deleted=null;render()}},900)}};$('#delete').addEventListener('click',del);cleanup.push(()=>$('#delete').removeEventListener('click',del));
 const down=()=>{state.replicas=Math.max(1,state.replicas-1);rep.value=state.replicas;state.deleted=null;render()};$('#scale-down').addEventListener('click',down);cleanup.push(()=>$('#scale-down').removeEventListener('click',down));
 const up=()=>{state.replicas=Math.min(5,state.replicas+1);rep.value=state.replicas;state.deleted=null;render()};$('#scale-up').addEventListener('click',up);cleanup.push(()=>$('#scale-up').removeEventListener('click',up));const done=()=>markComplete();root.querySelector('[data-mark-complete]').addEventListener('click',done);cleanup.push(()=>root.querySelector('[data-mark-complete]')?.removeEventListener('click',done));render();}
export function unmount(){cleanup.forEach(fn=>{try{fn()}catch{}});cleanup=[];}
